In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
np.__version__

'1.24.3'

In [8]:

a1 = np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np
a1 = np.array([1, 2, 3, 4], ndmin=5)
print(a1)
print('dimension is', a1.ndim)


[[[[[1 2 3 4]]]]]
dimension is 5


In [14]:

a1 = np.array([1,2,3,4])
print(a1[:3:2])

[1 3]


In [15]:
a = np.array([(1,2,3,4),(5,6,7,8)])
print(a[0:,3])

[4 8]


In [16]:
a = np.linspace(1,5,10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [8]:
import numpy as np

temperature_data = np.array([28.5, 30.2, 25.8, 29.3, 31.0, 27.6, 28.9])


print("Temperature recorded on 3rd day:", temperature_data[2])


temperature_subset = temperature_data[1:5]
print("Temperature from 2nd to 5th day:", temperature_subset)


average_temperature = np.mean(temperature_data)
print("Average temperature of the entire week:", average_temperature)


reshaped_temperature_data = temperature_data.reshape(2,4)
print("Reshaped temperature data:\n", reshaped_temperature_data)


for temp in temperature_data:
    if temp >= 30:
        print(f"{temp} degrees Celsius is a hot temperature.")
    else:
        print(f"{temp} degrees Celsius is not a hot temperature.")


additional_array = np.array([32.1, 20.5, 29.8, 33.2, 28.0, 31.5, 30.9])
combined_temperature_data = np.concatenate((temperature_data, additional_array))
print("Combined temperature data:\n", combined_temperature_data)


split_arrays = np.array_split(combined_temperature_data, 2)
print("Split arrays:")
print("Array 1:", split_arrays[0])
print("Array 2:", split_arrays[1])


Temperature recorded on 3rd day: 25.8
Temperature from 2nd to 5th day: [30.2 25.8 29.3 31. ]
Average temperature of the entire week: 28.75714285714286


ValueError: cannot reshape array of size 7 into shape (2,4)